#!/usr/bin/env bash
# Check if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
# Transfer file using scp with SSH key
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
