#!/usr/bin/env bash
# Update package list
sudo apt update

# Install nginx
sudo apt install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html


# Configure nginx to redirect /redirect_me to facebook.com with a 301 Moved Permanently
# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
