#!/usr/bin/env bash

# Function to handle SIGTERM signal
terminate() {
  echo "I am invincible!!!"
  exit 0
}

trap terminate SIGTERM

# Infinite loop with sleep 2 between iterations
while true
do
    if [ "$?" -eq 143 ]; then
        echo "Yes"
    fi
  echo "To infinity and beyond"
  sleep 2
  
done